# Control elbow using muscles
import sys
from tarfile import data_filter
import mujoco as m
import numpy as np
from simple_pid import PID
from muscle_torque_map import get_activation as get_single_muscle_activation
from muscle_co_contraction import get_activation
from muscle_co_contraction import optimize_muscles_activation

from plant_models import PlantPlotData
sys.modules['numpy'] = np  

import record
from tqdm import tqdm

IMG_HEIGHT = 1088
IMG_WIDTH = 1088
SIMLEN = 5  # seconds
FPS = 30
SEED = 1
TIMESTEP = 0.001
def main():

    spec = m.MjSpec.from_file("models/myo_sim/elbow/myoelbow_1dof6muscles_weighted.xml") #this model has gravity
    model = spec.compile()
    model.opt.timestep = TIMESTEP
    data = m.MjData(model)

    simstart = data.time

    states = []
    state_size = m.mj_stateSize(model, m.mjtState.mjSTATE_INTEGRATION)

    model.vis.global_.offwidth = IMG_WIDTH
    model.vis.global_.offheight = IMG_HEIGHT

    elbow_angle_series = []
    elbow_ref_series = []
    req_angle=55


    muscle_objs = [model.actuator(i) for i in range(6)]
    muscle_names = [muscle.name for muscle in muscle_objs]

    muscle_input_series = []
    torque_series = []
    torque_ref_series = []
    pd=plant_data()
    es=0


    # sim loop
    step_counter=0
    req_torque=0
    wrist=model.site("wrist")
    hand=model.body("r_ulna_radius_hand")
    lastcrl=np.zeros(6)

    with tqdm(total=SIMLEN*1.001) as pbar:

        balled=False
        while data.time - simstart < SIMLEN:#len(pd)-1:

            curr_angle = np.rad2deg(data.qpos[0].copy())     

            if data.time - simstart> 3 and not balled:
                balled=True
                ballgeom=spec.geom("baller")
                ballgeom.mass = 1.0
                print(ballgeom.mass)
                print("Added weight to the hand")
                model,data=spec.recompile(model,data)

                

            # apply ctrl
            if data.time - simstart < 3:
                req_torque, es = PI_control(curr_angle, req_angle, es)#pd[step_counter]#

                #data.ctrl[model.actuator("BIClong").id] = 0.15#get_single_muscle_activation("BIClong", curr_angle, req_torque)
                #data.ctrl[model.actuator("TRIlong").id] = 0.2
                data.ctrl=get_activation(curr_angle, req_torque)
                lastcrl=data.ctrl.copy()
            else:
                data.ctrl=lastcrl.copy()
                req_torque=0

            # save series
            actuator_input = data.ctrl.copy()
            elbow_angle_series.append((data.time, curr_angle))
            elbow_ref_series.append((data.time, req_angle))

            muscle_input_series.append((data.time, actuator_input))
            torque_series.append((data.time, data.qfrc_actuator.copy()+data.qfrc_passive.copy()))
            torque_ref_series.append((data.time, req_torque))

            # Save state every 1/FPS seconds for video rendering
            if len(states) < (data.time - simstart) * FPS:
                state_buffer = np.empty(state_size, dtype=np.float64)
                m.mj_getState(model, data, state_buffer, m.mjtState.mjSTATE_INTEGRATION)
                states.append(state_buffer.copy())


            # Step the simulation
            m.mj_step(model, data)
            pbar.update(data.time - simstart - pbar.n)
            #print(f"Simulation time: {time.time() - start} seconds")
            step_counter+=1


    #record.save_video(record.render_frames(model, states, IMG_HEIGHT, IMG_WIDTH, camera="side_view", time_series=elbow_angle_series, plot_title="Elbow Angle [degrees]"), "muscle_ol_ctrl_elbow", FPS)
    folder="muscle_cocontr_disturbance"
    record.plot_data(elbow_angle_series, folder+"/ol_elbow_angle", title="Disturbed without co-contraction",xlabel="Time [s]", ylabel="Angle [degrees]")
    record.plot_data(torque_series, folder+"/ol_joint_torque", title="Torque generated by muscle activations [Nm]", xlabel="Time [s]", ylabel="Torque [Nm]")#,ref_series=torque_ref_series)

    for j in range(len(muscle_input_series[0][1])):
        input_series_j = [(t, inputs[j]) for t, inputs in muscle_input_series]
        record.plot_data(input_series_j, f"{folder}/ol_muscle_input_{j}", muscle_names[j])
    print(f"Plots saved to ./plots/{folder}/ folder")


def P_control(angle, req_angle):
    """ Returns the TORQUE control signal for current timestep"""
    K=0.1
    return -K*(angle - req_angle)

def PI_control(angle, req_angle, error_sum, dt=0.001):
    """ Returns the TORQUE control signal and updated error sum """
    Kp = 0.15
    Ki = 0.3  # Tune this to eliminate steady-state error
    
    error = angle - req_angle
    error_sum += error * dt
    
    torque = -Kp * error - Ki * error_sum
    return torque, error_sum


def plant_data():
    """Returns a list of torques to apply every 1ms"""
    path = "./plant_data.json"
    with open(path, "r") as f:
        json = f.read()
    plant_data = PlantPlotData.model_validate_json(json)

    return plant_data.joint_data[1].input_cmd_torque

if __name__ == "__main__":
    main()