# Open loop muscular control for elbow

import json
import sys
from gymnasium import spec
import mujoco as m
import numpy as np
from simple_pid import PID
import muscle_co_contraction
from muscle_torque_map import get_activation
from muscle_co_contraction import get_activation

import muscle_torque_map
from plant_models import PlantPlotData
sys.modules['numpy'] = np  
import time

import record
from tqdm import tqdm

IMG_HEIGHT = 1088
IMG_WIDTH = 1088
SIMLEN = 4  # seconds
FPS = 30
SEED = 1
TIMESTEP = 0.001
def main():

    spec = m.MjSpec.from_file("models/myo_sim/elbow/myoelbow_1dof6muscles.xml") #this model has gravity
    model = spec.compile()
    model.opt.timestep = TIMESTEP
    data = m.MjData(model)

    simstart = data.time

    states = []
    state_size = m.mj_stateSize(model, m.mjtState.mjSTATE_INTEGRATION)

    model.vis.global_.offwidth = IMG_WIDTH
    model.vis.global_.offheight = IMG_HEIGHT
    elbow_angle_series = []
    elbow_ref_series = []


    start= time.time()
    step_count = 0

    path = "./plant_data.json"
    with open(path, "r") as f:
        json = f.read()
    plant_data = PlantPlotData.model_validate_json(json)

    list_torques = plant_data.joint_data[1].input_cmd_torque

    muscle_objs = [model.actuator(i) for i in range(6)]
    muscle_names = [muscle.name for muscle in muscle_objs]
    bra= model.actuator("BRA")


    muscle_force_series = []
    muscle_input_series = []
    torque_series = []

    # sim loop
    with tqdm(total=SIMLEN) as pbar:
        while data.time - simstart < SIMLEN:

            # apply ctrl
            curr_angle = np.rad2deg(data.qpos[0].copy())

            

            elbow_angle_series.append((data.time, curr_angle))

            actuator_force = data.actuator_force.copy()
            actuator_input = data.ctrl.copy()
            elbow_angle_series.append((data.time, curr_angle))
            muscle_force_series.append((data.time, actuator_force))
            muscle_input_series.append((data.time, actuator_input))
            torque_series.append((data.time, data.qfrc_actuator.copy()))

            # Save state every 1/FPS seconds for video rendering
            if len(states) < (data.time - simstart) * FPS:
                state_buffer = np.empty(state_size, dtype=np.float64)
                m.mj_getState(model, data, state_buffer, m.mjtState.mjSTATE_INTEGRATION)
                states.append(state_buffer.copy())


            # Step the simulation
            m.mj_step(model, data)
            step_count += 1
            pbar.update(data.time - simstart - pbar.n)
            #print(f"Simulation time: {time.time() - start} seconds")


    #record.save_video(record.render_frames(model, states, IMG_HEIGHT, IMG_WIDTH, camera="side_view", time_series=elbow_angle_series, plot_title="Elbow Angle [degrees]"), "muscle_Pctrl_elbow", FPS)
    record.plot_data(elbow_angle_series, "ol_muscle_ctrl/ol_elbow_angle", title="Elbow Angle [degrees]")
    record.plot_data(torque_series, "ol_muscle_ctrl/ol_joint_torque", title="Torque generated by muscle activation [Nm]")
    for j in range(len(muscle_force_series[0][1])):
        force_series_j = [(t, forces[j]) for t, forces in muscle_force_series]
        record.plot_data(force_series_j, f"ol_muscle_ctrl/ol_muscle_force_{j}", muscle_names[j])

    for j in range(len(muscle_input_series[0][1])):
        input_series_j = [(t, inputs[j]) for t, inputs in muscle_input_series]
        record.plot_data(input_series_j, f"ol_muscle_ctrl/ol_muscle_input_{j}", muscle_names[j])
    print("Plots saved to ./plots/ol_muscle_ctrl/ folder")


if __name__ == "__main__":
    main()